auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s

schema_config:
  configs:
    - from: 2023-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/tsdb-index
    cache_location: /loki/tsdb-cache
  filesystem:
    directory: /loki/chunks

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules
  alertmanager_url: ""
  ring:
    kvstore:
      store: inmemory
  enable_api: true

limits_config:
  split_queries_by_interval: 24h
  max_query_parallelism: 32
  ruler_max_rules_per_rule_group: 20
  ruler_max_rule_groups_per_tenant: 20

compactor:
  working_directory: /loki/compactor
  compaction_interval: 10m
