server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    tenant_id: default

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["app=demo-app"]

    relabel_configs:
      # Common labels that match Prometheus
      - source_labels: ["__meta_docker_container_label_app"]
        target_label: "service_name"
      - source_labels: ["__meta_docker_container_name"]
        target_label: "container_name"
      # Add environment label
      - target_label: "environment"
        replacement: "dev"
      # Add region label
      - target_label: "region"
        replacement: "us-west-2"

      # Loki-specific labels
      - target_label: "log_source"
        replacement: "docker"
      - target_label: "host"
        replacement: "${HOSTNAME}"

    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            service_name: service_name
            environment: environment
            region: region
            method: method
            path: path
            status: status
            request_time: request_time
