global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: "demo-app"
    static_configs:
      - targets: ["demo-app:80"]
        labels:
          service_name: "demo-app" # Maps to service.name in OTel
          environment: "dev"
          region: "us-west-2"
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [service_name]
        target_label: job # For OTel compatibility

  - job_name: "nginx-metrics"
    static_configs:
      - targets: ["demo-app:80"]
        labels:
          service_name: "nginx"
          component: "web"
          team: "platform"
